"""This type stub file was generated by pyright."""

__copyright__ = ...
__license__ = ...

class AmazonOrdersError(Exception):
    """Raised when a general ``amazon-orders`` error has occurred."""

    ...

class AmazonOrdersNotFoundError(AmazonOrdersError):
    """Raised when an Amazon page is not found."""

    ...

class AmazonOrdersAuthError(AmazonOrdersError):
    """Raised when an ``amazon-orders`` authentication error has occurred."""

    ...

class AmazonOrdersEntityError(AmazonOrdersError):
    """Raised when an ``amazon-orders`` entity parsing error has occurred."""

    ...
