"""This type stub file was generated by pyright."""

from abc import ABC
from typing import Any, Dict, Optional, TYPE_CHECKING
from bs4 import Tag
from amazonorders.conf import AmazonOrdersConfig
from amazonorders.session import AmazonSession

__copyright__ = ...
__license__ = ...
if TYPE_CHECKING: ...

class AuthForm(ABC):
    """The base class of an authentication ``<form>`` that can be submitted.

    The base implementation will attempt to auto-solve Captcha. If this fails, it will
    use the default image view to show the Captcha prompt, and it will also pass the
    image URL to :func:`~amazonorders.session.IODefault.prompt` as ``img_url``.
    """
    def __init__(
        self,
        config: AmazonOrdersConfig,
        selector: Optional[str],
        error_selector: Optional[str] = ...,
        critical: bool = ...,
    ) -> None: ...
    def select_form(self, amazon_session: AmazonSession, parsed: Tag) -> bool:
        """Using the ``selector`` defined on this instance, select the ``<form>`` for the given :class:`~bs4.Tag`.

        :param amazon_session: The ``AmazonSession`` on which to submit the form.
        :param parsed: The ``Tag`` from which to select the ``<form>``.
        :return: Whether the ``<form>`` selection was successful.
        """
        ...

    def fill_form(self, additional_attrs: Optional[Dict[str, Any]] = ...) -> None:
        """Populate the ``data`` field with values from the ``<form>``, including any additional attributes passed.

        :param additional_attrs: Additional attributes to add to the ``<form>`` data for submission.
        """
        ...

    def submit(self) -> None:
        """Submit the populated ``<form>``."""
        ...

    def clear_form(self) -> None:
        """Clear the populated ``<form>`` so this class can be reused."""
        ...

class SignInForm(AuthForm):
    def __init__(
        self,
        config: AmazonOrdersConfig,
        selector: Optional[str] = ...,
        solution_attr_key: str = ...,
    ) -> None: ...
    def fill_form(self, additional_attrs: Optional[Dict[str, Any]] = ...) -> None: ...

class MfaDeviceSelectForm(AuthForm):
    """This will first echo the ``<form>`` device choices, then it will pass the list of choices
    to :func:`~amazonorders.session.IODefault.prompt` as ``choices``. The value passed to
    :func:`~amazonorders.session.IODefault.prompt` will be a ``list`` of  the ``value`` from
    each of ``input`` tag.
    """
    def __init__(
        self,
        config: AmazonOrdersConfig,
        selector: Optional[str] = ...,
        solution_attr_key: str = ...,
    ) -> None: ...
    def fill_form(self, additional_attrs: Optional[Dict[str, Any]] = ...) -> None: ...

class MfaForm(AuthForm):
    def __init__(
        self,
        config: AmazonOrdersConfig,
        selector: Optional[str] = ...,
        solution_attr_key: str = ...,
    ) -> None: ...
    def fill_form(self, additional_attrs: Optional[Dict[str, Any]] = ...) -> None: ...

class CaptchaForm(AuthForm):
    def __init__(
        self,
        config: AmazonOrdersConfig,
        selector: Optional[str] = ...,
        error_selector: Optional[str] = ...,
        solution_attr_key: str = ...,
    ) -> None: ...
    def fill_form(self, additional_attrs: Optional[Dict[str, Any]] = ...) -> None: ...
