"""This type stub file was generated by pyright."""

from typing import List, Optional
from amazonorders.conf import AmazonOrdersConfig
from amazonorders.entity.order import Order
from amazonorders.session import AmazonSession

__copyright__ = ...
__license__ = ...
logger = ...

class AmazonOrders:
    """Using an authenticated :class:`~amazonorders.session.AmazonSession`, can be used to query Amazon
    for Order details and history.
    """
    def __init__(
        self,
        amazon_session: AmazonSession,
        debug: Optional[bool] = ...,
        config: Optional[AmazonOrdersConfig] = ...,
    ) -> None: ...
    def get_order_history(
        self,
        year: int = ...,
        start_index: Optional[int] = ...,
        full_details: bool = ...,
    ) -> List[Order]:
        """Get the Amazon order history for the given year.

        :param year: The year for which to get history.
        :param start_index: The index to start at within the history.
        :param full_details: Will execute an additional request per Order in the retrieved history to fully
            populate it.
        :return: A list of the requested Orders.
        """
        ...

    def get_order(self, order_id: str) -> Order:
        """Get the Amazon order represented by the ID.

        :param order_id: The Amazon Order ID to lookup.
        :return: The requested Order.
        """
        ...
