"""This type stub file was generated by pyright."""

from typing import List, Optional
from amazonorders.conf import AmazonOrdersConfig
from amazonorders.entity.transaction import Transaction
from amazonorders.session import AmazonSession

__copyright__ = ...
__license__ = ...
logger = ...

class AmazonTransactions:
    """Using an authenticated :class:`~amazonorders.session.AmazonSession`, can be used to query Amazon
    for Transaction details and history.
    """
    def __init__(
        self,
        amazon_session: AmazonSession,
        debug: Optional[bool] = ...,
        config: Optional[AmazonOrdersConfig] = ...,
    ) -> None: ...
    def get_transactions(self, days: int = ...) -> List[Transaction]:
        """Get the Amazon Transactions for the given number of days.

        :param days: The number of days worth of transactions to get.
        :return: A list of the requested Transactions.
        """
        ...
