"""This type stub file was generated by pyright."""

from typing import Any

from amazonorders.conf import AmazonOrdersConfig
from amazonorders.entity.transaction import Transaction
from amazonorders.session import AmazonSession

__copyright__ = ...
__license__ = ...
logger = ...

class AmazonTransactions:
    def __init__(
        self,
        amazon_session: AmazonSession,
        debug: bool | None = ...,
        config: AmazonOrdersConfig | None = ...,
    ) -> None: ...
    def get_transactions(
        self,
        days: int = ...,
        next_page_data: dict[str, Any] | None = ...,
        keep_paging: bool = ...,
    ) -> list[Transaction]:
        """Get Amazon Transaction history for a given number of days.

        :param days: The number of days worth of Transactions to get.
        :param next_page_data: If a call to this method previously errored out, passing the exception's
            :attr:`~amazonorders.exception.AmazonOrdersError.meta` will continue paging where it left off.
        :param keep_paging: ``False`` if only one page should be fetched.
        :return: A list of the requested Transactions.
        """
        ...
