"""This type stub file was generated by pyright."""

from typing import TypeVar, Union
from amazonorders.entity.seller import Seller
from bs4 import Tag
from amazonorders.conf import AmazonOrdersConfig
from amazonorders.entity.parsable import Parsable
import datetime as dt

__copyright__ = ...
__license__ = ...
logger = ...
ItemEntity = TypeVar("ItemEntity", bound="Item")

class Item(Parsable):
    title: str
    link: str
    price: Union[float, None]
    seller: Union[Seller, None]
    condition: Union[str, None]
    return_eligible_date: Union[dt.date, None]
    image_link: Union[str, None]
    quantity: Union[int, None]

    """An Item in an Amazon :class:`~amazonorders.entity.order.Order`."""
    def __init__(self, parsed: Tag, config: AmazonOrdersConfig) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __lt__(self, other: "Item") -> bool: ...
