"""This type stub file was generated by pyright."""

from typing import TypeVar

from amazonorders.conf import AmazonOrdersConfig
from amazonorders.entity.parsable import Parsable
from bs4 import Tag

__copyright__ = ...
__license__ = ...
logger = ...
OrderEntity = TypeVar("OrderEntity", bound="Order")

class Order(Parsable):
    def __init__(
        self,
        parsed: Tag,
        config: AmazonOrdersConfig,
        full_details: bool = ...,
        clone: OrderEntity | None = ...,
        index: int | None = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
