"""This type stub file was generated by pyright."""

from datetime import date
from typing import TypeVar

from amazonorders.conf import AmazonOrdersConfig
from amazonorders.entity.item import Item
from amazonorders.entity.parsable import Parsable
from amazonorders.entity.recipient import Recipient
from amazonorders.entity.shipment import Shipment
from bs4 import Tag

__copyright__ = ...
__license__ = ...
logger = ...
OrderEntity = TypeVar("OrderEntity", bound="Order")

class Order(Parsable):
    """An Amazon Order."""

    full_details: bool
    shipments: list[Shipment]
    items: list[Item]
    order_number: str
    order_details_link: str | None
    grand_total: float
    order_placed_date: date
    recipient: Recipient
    payment_method: str | None
    payment_method_last_4: str | None
    subtotal: float | None
    shipping_total: float | None
    free_shipping: float | None
    promotion_applied: float | None
    coupon_saving: float | None
    subscription_discount: float | None
    total_before_tax: float | None
    estimated_tax: float | None
    refund_total: float | None

    def __init__(
        self,
        parsed: Tag,
        config: AmazonOrdersConfig,
        full_details: bool = ...,
        clone: OrderEntity | None = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
